require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

deployment_target = '12.0'

target 'OpenloginReactNativeSdkExample' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'openlogin-react-native-sdk', :path => '../..'
  pod 'OpenLogin', :git => "https://github.com/torusresearch/openlogin-swift-sdk.git", :branch => "master"

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
#  use_flipper!({ 'Flipper' => '0.80.0' })
#  post_install do |installer|
#    installer.pods_project.targets.each do |target|
#      target.build_configurations.each do |config|
#        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
#      end
#    end
#    flipper_post_install(installer)
#  end

  post_install do |installer|
      installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
              end
          end
          project.build_configurations.each do |config|
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
          end
      end
  end
end


